/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c1c8c2",
        "tertiary": "#24241d",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-container": "#87aa97",
        "secondary-fixed": "#b4eee3",
        "inverse-on-surface": "#f3f0e9",
        "on-primary-fixed": "#002114",
        "surface-container-high": "#ebe8e1",
        "tertiary-container": "#3a3931",
        "on-secondary-container": "#346c64",
        "surface-dim": "#dcdad3",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00201c",
        "surface-tint": "#446554",
        "primary-fixed": "#c6ebd6",
        "inverse-primary": "#aacfba",
        "surface": "#fcf9f2",
        "primary-fixed-dim": "#aacfba",
        "on-surface-variant": "#414844",
        "primary": "#06291b",
        "secondary-fixed-dim": "#98d1c7",
        "tertiary-fixed": "#e6e2d7",
        "background": "#fcf9f2",
        "on-tertiary-container": "#a5a298",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#cac6bc",
        "outline": "#727973",
        "surface-container": "#f1eee7",
        "secondary": "#2f685f",
        "inverse-surface": "#31312c",
        "surface-container-highest": "#e5e2db",
        "on-tertiary-fixed": "#1c1c15",
        "on-surface": "#1c1c18",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2db",
        "surface-bright": "#fcf9f2",
        "on-tertiary-fixed-variant": "#48473f",
        "on-secondary-fixed-variant": "#124f48",
        "primary-container": "#1e3f30",
        "on-primary-fixed-variant": "#2c4d3e",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f6f3ec",
        "secondary-container": "#b1ebe0",
        "on-background": "#1c1c18",
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0284c7',
          600: '#0284c7',
          700: '#0369a1',
          900: '#0c4a6e',
        },
        slate: {
          850: '#151e2e',
          950: '#0b0f19',
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-2xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "margin-desktop": "3rem",
        "max-width-content": "72rem",
        "gutter-mobile": "1rem",
        "space-3xl": "4rem",
        "space-2xl": "3rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "title-md": ["17px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["44px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}

